# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('E', 'Email'), ('P', 'Telefone')], max_length=1, verbose_name='Tipo')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('YT', 'YouTube'), ('SL', 'SlideShare')], max_length=2, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='T\xedtulo')),
                ('media_id', models.CharField(max_length=255, verbose_name='Ref')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('url', models.URLField(verbose_name='Url')),
                ('description', models.TextField(blank=True, verbose_name='Descri\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'palestra',
                'verbose_name_plural': 'palestras',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('talk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Talk')),
                ('slots', models.IntegerField()),
                ('notes', models.TextField()),
            ],
            bases=('core.talk',),
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(to='core.Speaker', verbose_name='palestrante'),
        ),
        migrations.AddField(
            model_name='media',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Talk'),
        ),
        migrations.AddField(
            model_name='contact',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Speaker', verbose_name='palestrante'),
        ),
    ]
